// Generated by https://quicktype.io

export interface CryptoCoins {
	data: CryptoCoin[];
	timestamp: number;
}

export interface CryptoCoin {
	id: string;
	rank: string;
	symbol: string;
	name: string;
	supply: string;
	maxSupply: string;
	marketCapUsd: string;
	volumeUsd24Hr: string;
	priceUsd: string;
	changePercent24Hr: string;
	vwap24Hr: string;
	explorer: string;
}

