import { AppLayout } from "@/components/organisms/AppLayout";
import styles from "./styles.module.scss";
import { CardDashboard } from "@/components/molecules/CardDashboard";
import { FormData } from "@/types";
import { Wallet } from "@/components/molecules/Wallet";
import { Cryptocoins } from "@/services/cryptocoins";
import { Modal, ModalHandler } from "@/components/molecules/modals/Modal";
import { useRef } from "react";
import Head from "next/head";
import { CryptoForm } from "@/components/molecules/forms/CryptoForm/AddCrypto";


interface Props {
  cryptoCoins: Cryptocoins[];
  onSubmit: (formData: FormData) => void;
}

export default function Dashboard(props: Props) {
  const modalHandlerAddCrypto = useRef<ModalHandler>(null);

  function openAddCrypto() {
    modalHandlerAddCrypto.current?.close();
    modalHandlerAddCrypto.current?.open();
  }


	return (
		<AppLayout>
        <Head>
            <title>Coin Synch - Dashboard</title>

            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

      </Head>
         <Modal ref={modalHandlerAddCrypto}>
            <CryptoForm onSubmit={props.onSubmit} cryptoAdd={props.cryptoCoins} onNeedCrypto={openAddCrypto}/>
        </Modal>
			<div className={styles.bg}>
				<main className={styles.page_content}>
					<div className={styles.section}>
						<CardDashboard crypto={props.cryptoCoins}/>
					</div>
          <Wallet coinsblock={props.cryptoCoins} onAddCryptoClick={openAddCrypto}/>
				</main>
			</div>
		</AppLayout>
	);
}
