import { GetStaticProps } from "next";
import axios from "axios";
import { Footer } from "@/components/organisms/Footer";
import { Cryptocoins} from "@/services/cryptocoins";
import { TopCryptos } from "@/components/organisms/TopCryptos";
import { AboutUs } from "@/components//organisms/AboutUs";
import styles from "./Home.module.scss";

import Head from "next/head";
import { NewsLetter } from "@/components/molecules/NewsLetter";
import { Header } from "@/components/organisms/Header";
import { useEffect, useState } from "react";
import { getCryptos } from "@/api/cryptoApi";


interface Props {
  cryptos: Cryptocoins[];
}

export default function HomeComponent(props: Props) {



  return (
  <>
  <Head>
    <title>Coin Synch</title>

    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />

  </Head>
    <main className={styles.main}>
      <Header assets={props.cryptos} />
      <section className={styles.wave}></section>
      <AboutUs />
      <TopCryptos cryptos={props.cryptos} />
      <NewsLetter />
      <Footer />
    </main>
  </>

  );
}

export const getStaticProps: GetStaticProps = async () => {
  const cryptosData = await getCryptos();
  return {
    props: {
      cryptos: cryptosData
    },
    revalidate: 60 // 24 horas em segundos
  };
};
