import { GetStaticProps } from "next";
import axios from "axios";
import { Footer } from "@/components/organisms/Footer";
import { CryptoCoin, CryptoCoins } from "@/services/cryptocoin";
import { TopCryptos } from "@/components/organisms/TopCryptos";
import { AboutUs } from "@/components//organisms/AboutUs";
import styles from "./Home.module.scss";

import Head from "next/head";
import { NewsLetter } from "@/components/molecules/NewsLetter";
import { Header } from "@/components/organisms/Header";


interface Props {
  assets: CryptoCoin[];
}

export default function HomeComponent(props: Props) {

  return (
  <>
  <Head>
    <title>Coin Synch</title>

    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />

  </Head>
    <main className={styles.main}>
      <Header assets={props.assets} />
      <section className={styles.Wave}></section>
      <AboutUs />
      <TopCryptos blockchains={props.assets} />
      <NewsLetter />
      <Footer />
    </main>
  </>

  );
}

export const getStaticProps: GetStaticProps<Props> = async (context) => {


  const COINSAPI_URI = "https://api.coincap.io/v2"
  const CONFIG = {
    method: 'GET',
    header: {
      // "X-CoinAPI-Key": "E687BA43-61A4-4909-A613-A3147AF94732",
      "Content-Type": "application/json; charset=utf-8"
    }
  }
  const response = await axios.get<CryptoCoins>(`${COINSAPI_URI}/assets`, CONFIG);
  const data = response.data.data;
  data.length = 20;
  return {
    props: {
      assets: response.data.data,
    },
    revalidate: 60,
  };
};
